### ISSUE TITLE
TODO (Incomplete)

### ISSUE THREAD

**Issue by anuragk47** [materialos/CM12-Theme#79]
**Modifications/Improvements to existing apps**
- [ ] Dialer: cyan and yellow color scheme
- [ ] Dialer: modern search bar like new G+
- [ ] Dialer: Change only required drawables and dimens
- [ ] Contacts: Theme like dialer

**New apps to theme**
- [ ] Instagram
- [ ] Twitter
- [ ] Cyngn gallery
- [ ] Cyngn audiofx
