### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anuragk47** [materialos/CM12-Theme#80]
ASSIGNED:
- [ ] Add final wallpaper and lock screen: Nils Urbanus
- [ ] Complete Theme Chooser theme: Anurag

UNASSIGNED:
- [ ] Edit weather icons by Naman Rastogi
  - First need to get AI's from Naman and add them to the Icons Repo
  - Then need to ask someone from the Design Team to edit the icons
- [ ] Complete Snapchat Pull Request by Kyler
