### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by anuragk47** [materialos/CM12-Theme#83]
## Development
- [ ] Add N style fork as an arcus variant
- [ ] Add PA style circular battery icon after asking permission
- [ ] Complete settings app theme and fix its bugs (assigned to @anonymas )
- [ ] Fix recents view in some ROMs
## Design
- [ ] Add new weather icons from Naman Rastogi (waiting for icons from NamanRastogi)
- [ ] Add final wallpaper and lock screen (waiting for wallpaper and lock screen from Design Team)
- [ ] In file manager replace file type icons with edited ones of same dimensions as in source ,they look weird right now (waiting for edited icons from Nils Urbanus)

**Comment by crutchcorn** [comment]
Do we have permission to use the N style fork?

**Comment by anuragk47** [comment]
@crutchcorn it's basically a few changes in dimens of systemui which both me and @Porasjeet have done many times before. But the fact that someone decided to fork and add it just makes it more convenient for us to add it as an arcus variant. And it's good to see community involvement in the development. And don't we have permission to use all forks by default according to Github?

**Comment by boswelja** [comment]
I can bring N style in to the Substratum variant too :)
